- name: Backup PostgreSQL Database
  hosts: remoteServers
  become: yes
  gather_facts: no
  vars:
    db_user: "customize_db_user"
    db_password: "customize_db_password"
    db_name: "customize_db_name"
    db_host: "customize_db_host"
    db_port: "customize_db_port"
    backup_path: "/path/to/backup"
    backup_file: "{{ db_name }}_{{ lookup('pipe', 'date +%F') }}.gz"

  tasks:
    - name: Ensure Backup Directory exists
      file:
        path: "{{ backup_path }}"
        state: directory
        mode: '0755'

    - name: Set up PostgreSQL Password File
      copy:
        dest: "/root/.pgpass"
        content: |
          {{ db_host }}:{{ db_port }}:*:{{ db_user }}:{{ db_password }}
        mode: '0600'
    
    - name: Dump PostgreSQL Databases
      command: >
        pg_dump -U {{ db_user }} -d {{ db_name }} -h {{ db_host }} | gzip > {{ backup_path }}/{{ backup_file }}
      environment:
        PGPASSFILE: "/root/.pgpass"

    - name: Remove .pgpass file
      file:
        path: "/root/.pgpass"
        state: absent